language: python
python:
  - "2.7"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
script:
    - py.test # or py.test for Python version 3.5 and below
after_success:
    - coveralls